FROM bogaotory/apples
MAINTAINER Bo Gao <bogao@dcs.warwick.ac.uk>

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        # python3 \
        # python3-setuptools \
        # python3-dev \
        # python3-numpy \
        # python3-scipy \
        # python-pandas \
        wget \
        # bedtools \
        samtools

RUN cd /tmp \
 && wget https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz \
 && tar -zxvf bedtools-2.25.0.tar.gz \
 && cd bedtools2 \
 && make \
 && make install

RUN wget https://www.python.org/ftp/python/3.4.5/Python-3.4.5.tar.xz \
 && tar xJf ./Python-3.4.5.tar.xz \
 && cd Python-3.4.5 \
 && ./configure --prefix=/opt/python3.4 \
 && make \
 && make install \
 && ln -s /opt/python3.4/bin/python3.4 /usr/bin/python3.4 \
 && ln -s /opt/python3.4/bin/python3 /usr/bin/python3

RUN  /opt/python3.4/bin/easy_install-3.4 numpy \
 && /opt/python3.4/bin/easy_install-3.4 pandas

# Seaweeds dependencies
RUN apt-get install -y --no-install-recommends \
		libtbb-dev \
		libboost-regex1.48.0 \
		libboost-program-options1.48.0

# RUN easy_install3 pandas numpy
# ENTRYPOINT ["bash", "/apples/wrapper_de_rbh.sh"]